---

  - name: Rebooting host!
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: Wait for the reboot...
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
